### ISSUE TITLE
simplifying-statespace: Moving action types to parent task?

### ISSUE THREAD

**Issue by sparr1** [mlanden/Maple-RAMDP#7]
Does that move make sense? Tasks should be parent-task agnostic, and the action type/parameters already reflect that if I recall correctly.  Moving the action types to the parent task folder just leads to unnecessary code duplication in my opinion (Get-navactiontype vs Put-navactiontype). Is there a good reason for this move/duplication?

**Comment by ShawnSquire** [comment]
There's actually not a duplication in code, which should show why the Action Types need to be moved to the actual tasks which call them.

1. Tasks are still parent-task agnostic, but my commit message was worded awkwardly. In fact, the `ActionType`s are just the actions for the tasks. Get / Put have two actions each, and each one is parameterized, hence needing a unique `ActionType` and not a `UniversalActionType`.

2. Each ActionType needs an `allApplicableActions` which takes a state as a parameter. The state differs between `get.NavigateActionType` and `put.NavigateActionType` because they expect a `TaxiGetState` and `TaxiPutState` respectively. Compare [one](https://github.com/mlanden/Maple-RAMDP/blob/5b02f09b7e3eb67a6a684841b04bc87e053d702a/src/taxi/hierarchies/tasks/get/NavigateActionType.java#L27) and [two](https://github.com/mlanden/Maple-RAMDP/blob/5b02f09b7e3eb67a6a684841b04bc87e053d702a/src/taxi/hierarchies/tasks/put/NavigateActionType.java#L27) to see what I mean.

3. Otherwise, they are effectively the same, so it would be wonderful if there could be a way to simplify this code to not need two. But, since the states are the same and there's no guarantee that both states will have the same methods available (i.e., calling `getLocations` on an arbitrary state that isn't AMDP specific to either get or put). The only other option was the one we are migrating away from, which is making Get / Put the same AMDP so their states are equivalent, which makes passing into Nav trivial.

4. This does cause oddities, like when constructing the hierarchy, there are effectively two Nav `ActionType`s to call. Again, this makes sense since both action types are expecting a different state representation. Luckily, they should both call the same Navigate AMDP if everything goes like it should.

I'm still debugging it. It's not crashing anymore, but I don't think it's running. It was late when I finished it, so there's probably a few more things I need to do.

**Comment by sparr1** [comment]
Well, that does make it not as straightforward as I thought, although I'm still not entirely sure that this is necessary. I will mull it over while looking closely at the code and report back.

**Comment by sparr1** [comment]
The quickest fix I can think of is to make the various `GroundedTask` states (`TaxiGetState` and `TaxiPutState`) with parameterized actions implement an interface which clearly announces the methods available. For example, `TaxiGetState` and `TaxiPutState` could both implement `locationParameterizable`, which is an interface with `getLocationParameters()`. This should solve the problem, and facilitate explicit parameterization that doesn't involve one-of methods with unclear purpose.

**Comment by ShawnSquire** [comment]
We discussed this in person, agreeing that interfaces provide part of the benefit by allowing `ActionType`s to be stored with the target task with a generic reference to the interface. All calling parent tasks will reference the `ActionType` from this action.

There are some issues to this method, however:

1. It couples the tasks in the hierarchy by forcing references by one task in the hierarchy to another just to reference the `ActionType`

2. It may only work if the state abstraction is standard among all calling tasks. If the states calling the `ActionType` differ by their state representation, it may create issues in how the `allApplicableActions` is implemented.

3. Shielding can not reliably occur at this level. We would need to implement a different method for shielding in a different location to fully parameterize all the methods.

In the meantime, [a commit](https://github.com/mlanden/Maple-RAMDP/commit/ccacc60e837a1d192b3a795d3d6c85e85545f5f7) has been pushed to paramterize `NavigateActionType` as a beginning example.
